name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.12
    - run: poetry install
    - run: poetry run pytest
